#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create \
	--name builder \
	--driver docker-container \
	--platform linux/amd64,linux/arm64 \
	--use
docker buildx inspect --bootstrap
